name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  workflow_dispatch: # Allows manual run of the workflow

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: dihanhassan # Replace with your GitHub username
          outputs: dist/snake.svg

      - name: Commit and push Snake animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated Snake animation [skip ci]"
          file_pattern: "dist/snake.svg"
